# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
title: Simple
subTitle: 临渊羡鱼，不如退而结网！
description: 这是 Frank 的第一个博客，它是基于 Jekyll 搭建起来的。在这里，用来记录我想要记录的时刻。
url: "http://loumingjie.cn/myblog"
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /myblog/index.html
  - text: 文章归档
    url: /myblog/archives.html
  - text: 作品
    url: /myblog/works.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /myblog/themes/violet/images/hdbg01.jpg
  - item: /myblog/themes/violet/images/hdbg02.jpg
  - item: /myblog/themes/violet/images/hdbg03.jpg
  - item: /myblog/themes/violet/images/hdbg04.jpg
  - item: /myblog/themes/violet/images/hdbg05.jpg
  - item: /myblog/themes/violet/images/hdbg06.jpg
  - item: /myblog/themes/violet/images/hdbg07.jpg

#关注我
follow:
  # - class: fa-google-plus
  #   url: http://www.zhanxin.info
  # - class: fa-facebook
  #   url: http://www.zhanxin.info
  - class: fa-github
    url: http://github.com/loudou140806
  - class: fa-weibo
    url: http://weibo.com/2391737244/profile?rightmod=1&wvr=6&mod=personinfo
  # - class: fa-renren
  #   url: http://www.zhanxin.info
  # - class: fa-pinterest
  #   url: http://www.zhanxin.info
  # - class: fa-twitter
  #   url: http://www.zhanxin.info
  # - class: fa-rss
  #   url: http://www.zhanxin.info

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
duoshuo:
  config: true
  id: loudou140806